permissions.easy
permissions.paranoid
permissions.secure

https://bugzilla.suse.com/show_bug.cgi?id=1056764

- permissions - copy dbus-daemon-launch-helper from / to /usr

---

permissions.paranoid
permissions.secure

permissions on sshd_config (secure/paranoid)

Stricter permissions on cron directories (paranoid) and stricter

---

permissions.secure

Fixed misleading comment (missing not)
Fixed 1 spelling mistake.

Misleading comment fix

---

permissions.easy
permissions.paranoid
permissions.secure

Singularity 3 has received a security review (bsc#1128598).
Signed-off-by: Egbert Eich <eich@suse.com>

singluarity: Add starter-suid for version 3.2.0

---

permissions.easy
permissions.paranoid
permissions.secure

Small fixes for iputils (boo#1140991, boo#1140993, boo#1140994).

iputils capabilities fixes

---

chkstat.c
permissions
permissions.easy
permissions.paranoid
permissions.secure

In the future we want to avoid patches in the OBS package and directly use the GitHub branch for creating updates in older codestreams.
It turned out that we've diverged in both directions, there are patches in the package that aren't in the branch but there are also commits in the branch that aren't in the package. The following two commits are not currently part of the package:
- c5d656e8e11e607f7040c0b5ddb1d9efbcb19f92
- 6ab01615b89404e92e9e865fa838ebe6f9ffc71d
After this PR is merged we should be able to clean up the SLE-15-SP1:Update/permissions package from the SLE-15-SP1 branch.

Synchronize SLE-15-SP1 branch with SLE-15-SP1:Update package

---

Makefile
chkstat.c

SLE-11-SP3: Makefile: fix $suseconfigdir

---

Makefile
chkstat.c
tests/regtest.py

somehow I forgot to do the pull request for this branch between all the other ones

SLE-15-SP2 back ports

---

permissions.paranoid

Remove setuid bit for newgidmap and newuidmap in paranoid profile

---

etc/permissions
profiles/permissions.easy
profiles/permissions.paranoid
profiles/permissions.secure

First round of cleanup changes that resulted from the whitelist checker findings.

Cleanup of Profiles

---

permissions.easy
permissions.paranoid
permissions.secure

(cherry picked from commit 7d5aac79807fd4a2350843cd993a9c695b850af7)

15-SP1: whitelist WMP (bsc#1161335, bsc#1176625)

---

permissions.easy
permissions.paranoid
permissions.secure

(cherry picked from commit 7d5aac79807fd4a2350843cd993a9c695b850af7)

15-GA: whitelist WMP (bsc#1161335, bsc#1176625)

---

profiles/permissions.easy
profiles/permissions.paranoid
profiles/permissions.secure

https://build.opensuse.org/request/show/858880

usbauth: Updated path for usbauth-npriv

---

permissions

Merge missing btmp fix to SLE-12-SP5 (bsc#1182899)

make btmp root:utmp (bsc#1050467)

---

profiles/permissions.easy
profiles/permissions.paranoid
profiles/permissions.secure

a couple of compatibility entries can now be removed

libexec cleanup

---

profiles/permissions.easy
profiles/permissions.paranoid
profiles/permissions.secure

https://build.opensuse.org/request/show/915242

KDE: libexecdir changes

---

zypper-plugin/permissions.py

Just changed a pronoun (he to they) and a couple of nouns to go along with it.

changed gendered pronouns

---

profiles/permissions.easy
profiles/permissions.paranoid
profiles/permissions.secure

This was removed via OBS sr#1065964.

profiles: remove dead opiepasswd entry

---

permissions.easy
permissions.paranoid
permissions.secure

https://bugzilla.suse.com/show_bug.cgi?id=1229329
reverts: https://bugzilla.suse.com/show_bug.cgi?id=1228548

cockpit: revert path change (bsc#1229329)

---

profiles/permissions.easy
profiles/permissions.paranoid
profiles/permissions.secure

https://bugzilla.suse.com/show_bug.cgi?id=1230950
see also https://bugzilla.suse.com/show_bug.cgi?id=1235461

profiles: whitelist nvidia-modprobe (bsc#1230950)
