openSUSE/permissions

- chkstat.8
- permissions.5
Nevertheless the man pages should probably be corrected more, for example CHECK_PERMISSIONS sysconfig variable does not seem to exist.
> typos in man-pgaes

- permissions.easy
- permissions.paranoid
- permissions.secure
In preparation for singularity 2.4 add /usr/lib/singularity/bin/start-suid to list.
Signed-off-by: Egbert Eich <eich@suse.com>
> Allow setuid root for singularity (group only) bsc#1028304

- permissions.easy
- permissions.paranoid
- permissions.secure
Capabilities for usage of Wireshark for non-root
easy: all users, for the desktop out of the box experience
secure: members of wireshark group
paranoid: no capabilities
[bsc#957624](https://bugzilla.opensuse.org/show_bug.cgi?id=957624)
> Capabilities for usage of Wireshark for non-root

- permissions.easy
- permissions.paranoid
- permissions.secure
permissions are the same as for ping.
NOTE: originally I wanted to add also capabilities arping,
but it could be used for ARP poisoning attacks.
Fixes: boo#1140994
Signed-off-by: Petr Vorel <pvorel@suse.cz>
> iputils: Add capability permissions for clockdiff

- Makefile
- etc/permissions
- man/chkstat.8
- man/permissions.5
- profiles/permissions.easy
- profiles/permissions.paranoid
- profiles/permissions.secure
- src/chkstat.cpp
- tests/regtest.py
Fixes relative symlinks, and reverts to the legacy behaviour that if the final path element is a link, it doesn't get followed.
Also merges #37 and #30.
> Fix symlink handling

- src/chkstat.cpp
on ARM/PPC/s390x, the comparison with EOF would always fail because
`(unsigned char)EOF != EOF`
> chkstat: fix readline() on platforms with unsigned char

- profiles/permissions.easy
- profiles/permissions.paranoid
- profiles/permissions.secure
I initially submitted this only to SLE-15-SP2 since that's where it was needed urgently. But we don't want to lose this whitelisting in future releases, so I guess we need this in `master` too even if the binary doesn't exist in factory.
(If we had separation of SLE/openSUSE I guess this is the first thing that'd be in the SLE only bucket.)
> whitelist WMP (bsc#1161335) in master

- chkstat.c
- permissions.easy
- permissions.paranoid
- permissions.secure
merge the patches from OBS into git, and backport of the recent CVE fixes to this code stream
chkstat.c is (practically) identical to SLE-15-SP1 afterwards, and the only difference of the profiles to current OBS state is the icinga stuff (which was half fixed already in git, but not forwarded to OBS)
> chkstat fixes for SLE-15-GA

- profiles/permissions.easy
- profiles/permissions.paranoid
- profiles/permissions.secure
This just duplicates every entry for `/usr/lib` with an additional one for `/us/libexec`. There's probably some packages that use the wrong RPM macro and therefore don't have an immediate need for the new whitelisted path.
IMO, it's still good to whitelist the new path in all cases - in the short term it makes it much easier for the packagers to fix their packages, and in the long-term we want to clean up the duplicate entries anyways (and we have scripts that tell us which of the entries to keep and which ones to drop).
> allow /usr/libexec in addition to /usr/lib (bsc#1171164)

- .gitignore
- Makefile
- src/chkstat.cpp
- src/chkstat.h
- src/formatting.cpp
- src/formatting.h
- src/utility.cpp
- src/utility.h
- tests/regtest.py
This finalizes my hackweek project to "rewrite chkstat". Based on the regression test suite I was now able to refactor the code base step by step to arrive at a new code base that is, I think, more digestible than what we had before.
I tried hard not to change program behaviour but in some spots it still happened:
- ealier long command line options could be specified using only a single `--` or a  double `-`. Now only `--` is supported any more. I'm not aware of any users (in code) of the single `-` variant.
- earlier duplicate specifications of the same command line option was tolerated, overwriting previous values found on the command line. Now only a single specification is allowed any more.
- earlier the "header" was only printed when an actual mismatch was found. Now the header is …
> Refactoring of chkstat into a modern C++ Program

- profiles/permissions.easy
- profiles/permissions.paranoid
- profiles/permissions.secure
texlive has long shipped `/usr/lib/mktex/public`. It got away without being whitelisted here by packaging it `0755` in the RPM but with `%set_permissions` that ended up setting the setgid bit through the whitelisted `/etc/permissions.d/texlive`.
@jsegitz please review since you're most familiar with the texlive packaging.
> whitelist texlive public binary (bsc#1171686)

- profiles/permissions.easy
- profiles/permissions.paranoid
- profiles/permissions.secure
Fixes https://bugzilla.opensuse.org/show_bug.cgi?id=1171164
> dbus-1: adjust to new libexec dir location (bsc#1171164)

- etc/permissions.local
The immediate concern was to remove the reference to the removed `/etc/permissions.*` paths.
I've also removed the examples, because they are ancient and I have little confidence they are still correct.
I've also changed the explanation of why changes in this file might not apply in practice. Still not completely happy with the result, but hopefully it's an improvement.
> rework permissions.local text (boo#1173221)

- tools/list_permissions.py
Keeping track of the settings for paths spread over up to four different
configuration files is often difficult. This new script gathers
information from all available files in the repository and prints out a
condensed overview of the present configuration for individual paths.
> list_permissions: new tool for better path configuration overview

- profiles/permissions.easy
- profiles/permissions.paranoid
- profiles/permissions.secure
- mtr requires capabilities on `/usr/sbin/mtr-packet` instead of `/usr/sbin/mtr` since version 0.88.
> etc/permissions: fix mtr permission

- profiles/permissions.easy
- profiles/permissions.paranoid
- profiles/permissions.secure
Since cockpit was also moved to /usr/libexec, we need to add the new path to fix building the package
> Add /usr/libexec for cockpit-session as new path

- profiles/permissions.easy
- profiles/permissions.paranoid
- profiles/permissions.secure
The new package will place the two paths into /usr/libexec now.
> usbauth: drop compatibility variable for libexec

- permissions
Patch was merged to SLE-12-SP2 and origin/SLE-15-GA and newer, but not to SLE-12-SP4 and SLE-12-SP5 (bsc#1182899).
> make btmp root:utmp (bsc#1050467)

- permissions
systemd since v234 creates "/var/log/lastlog" as
"/var/log/lastlog 0664 root utmp -"
https://github.com/openSUSE/systemd/commit/aff804febc31d9f0d0f98ccc3cdf9f89dd64409c
> make lastlog root:utmp (bsc#1182899)

- profiles/permissions.easy
- profiles/permissions.paranoid
- profiles/permissions.secure
linter says:
W: [path-in-migration-mode] /sbin/mount.nfs
→ exists as /usr/sbin/mount.nfs
> mount.nfs: switch from migration mode to fixed path in /usr/sbin

- permissions.easy
- permissions.paranoid
- permissions.secure
This does into a new branch SLE-15-SP4. We will need to fork a new codestream for this SP.
> backport whitelisting for SLE-15-SP4 (bsc#1196884)

- chkstat.c
The backport of the group-writable security fix is missing this important bit, namely, that the file actually needs to be group-writable to trigger the logic.
This causes false positives if parent directories have a non-root group assigned but are not actually writable by that group.
> fix regression introduced by backport of security fix (bsc#1203911)

- permissions.easy
- permissions.paranoid
- permissions.secure
On main/master branch this was fixed more elegantly via %{lib_dirs}, which however is not yet available on SLE. Duplicate the entries instead.
> permissions for enlightenment helper on 32bit arches (bsc#1194047)

- profiles/permissions.easy
- profiles/permissions.paranoid
- profiles/permissions.secure
- apptainer is now supporting a mode without setuid-root (bsc#1206521)
- kdesud also supports operation without setgid (bsc#1206522)
> profiles: remove outdated kdesud, apptainer entries

- permissions.easy
- permissions.paranoid
- permissions.secure
Backport postfix SUID whitelisting to Leap 15.2, as requested in https://bugzilla.suse.com/show_bug.cgi?id=1206738
Most recent audit: https://bugzilla.opensuse.org/show_bug.cgi?id=1201385
> Backport postfix to Leap 15.2 (bsc#1206738)

- permissions.easy
- permissions.paranoid
- permissions.secure
Backport postfix SUID whitelisting to SLE-15-SP2, as requested in https://bugzilla.suse.com/show_bug.cgi?id=1206738
Most recent audit: https://bugzilla.opensuse.org/show_bug.cgi?id=1201385
> Backport postfix to SLE-15-SP2 (bsc#1206738)

- profiles/permissions.easy
- profiles/permissions.paranoid
- profiles/permissions.secure
This daemon used to run as root but it actually only required two file capabilities.
https://bugzilla.suse.com/show_bug.cgi?id=1207654
> profiles: whitelist kismet capabilities (bsc#1200954)

- man/chkstat.8
- src/chkstat.cpp
- src/chkstat.h
- src/entryproc.cpp
- src/environment.h
In some environments /proc is not available (details are available in https://bugzilla.suse.com/show_bug.cgi?id=1219736). This introduces the ability to force an insecure operation mode by settting CHKSTAT_FORCE_INSECURE_MODE_IF_NO_PROC
> CHKSTAT_ALLOW_INSECURE_MODE_IF_NO_PROC allows modification without /proc

- permissions.easy
- permissions.paranoid
- permissions.secure
New pull request for the new `SLE-15-SP6` branch.
`/usr/lib/cockpit-session` moved to
`/usr/lib/cockpit/cockpit-session`
> cockpit: moved setuid executable (bsc#1228548)

- permissions.easy
- permissions.paranoid
- permissions.secure
https://bugzilla.suse.com/show_bug.cgi?id=1246776
previously reviewed in: 
https://bugzilla.suse.com/show_bug.cgi?id=1230950
> nvidia-modprobe: SLE-15-SP4 backport (bsc#1246776)
